sudo: true

language: python

cache:
  - pip
  - ccache

env:
  global:
    - TOX_TESTENV_PASSENV="LD_RUN_PATH,LD_LIBRARY_PATH"
    - MAKEFLAGS="--quiet"

before_install:
  # PPA for NGINX with a separate OpenSSL 1.0.2 package
  - sudo add-apt-repository -y ppa:ondrej/nginx-mainline
  # PPA with recent autoconf and automake
  - sudo add-apt-repository -y ppa:ondrej/autotools
  - sudo apt-get update -qq
  - sudo apt-get install -y libssl-dev openssl
  - sudo apt-get install -y autoconf automake

install:
  - gcc -v
  - autoconf --version
  - automake --version
  - libtool --version
  - openssl version
  - ./.travis/install-jansson.sh
  - pkg-config jansson --cflags --libs
  - ./.travis/install-jose.sh
  # install Python base dependencies
  - pip install --upgrade pip setuptools
  - pip --version
  - pip install tox cython
  - tox --version
  - cython --version

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    #- python: 3.4
    #  env: TOXENV=py34
    #- python: 3.5
    #  env: TOXENV=py35
    #- python: 3.5
    #  env: TOXENV=doc
    #- python: 2.7
    #  env: TOXENV=pep8py2
    #- python: 3.5
    #  env: TOXENV=pep8py3

script:
  - echo "Testing"
  - tox
