sudo: true

language: python

cache:
  - pip
  - ccache
  - directories:
    - ${HOME}/joselib

env:
  global:
    - PACKAGEHOME="${HOME}/joselib"
    - CPPFLAGS="-I${PACKAGEHOME}/include"
    - LDFLAGS="-L${PACKAGEHOME}/lib"
    - LD_RUN_PATH="${PACKAGEHOME}/lib"
    - LD_LIBRARY_PATH="${PACKAGEHOME}/lib"
    - PKG_CONFIG_PATH="${PACKAGEHOME}/lib/pkgconfig"
    - PATH="${PACKAGEHOME}/bin:$PATH"
    - SSL_CERT_DIR="/etc/ssl/certs"
    - SSL_CERT_FILE="/etc/ssl/certs/ca-certificates.crt"
    - TOX_TESTENV_PASSENV="LD_RUN_PATH,LD_LIBRARY_PATH"
    - MAKEFLAGS="--quiet"

before_install:
  # PPA for NGINX with a separate OpenSSL 1.0.2 package
  - sudo add-apt-repository -y ppa:ondrej/nginx-mainline
  # PPA with recent autoconf and automake
  - sudo add-apt-repository -y ppa:ondrej/autotools
  - sudo apt-get update -qq
  - sudo apt-get install -y libssl-dev openssl
  - sudo apt-get install -y autoconf automake-1.15

install:
  - gcc -v
  - mkdir -p $PACKAGEHOME
  # Ubuntu Trusty has OpenSSL 1.0.1 but jose requires 1.0.2+
  #- ./.travis/install-openssl.sh
  - openssl version
  - pkg-config openssl --cflags --libs
  # jansson
  - ./.travis/install-jansson.sh
  - pkg-config jansson --cflags --libs
  # Ubuntu has outdated automake and autoconf, too
  #- ./.travis/install-autoconf.sh
  #- ./.travis/install-automake.sh
  #- ./.travis/install-libtool.sh
  - autoconf --version
  - automake --version
  # now jose with updated autotools
  - ./.travis/install-jose.sh
  # install Python base dependencies
  - pip install --upgrade pip setuptools
  - pip --version
  - pip install tox
  - tox --version
  - pip install cython
  - cython --version

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    #- python: 3.4
    #  env: TOXENV=py34
    #- python: 3.5
    #  env: TOXENV=py35
    #- python: 3.5
    #  env: TOXENV=doc
    #- python: 2.7
    #  env: TOXENV=pep8py2
    #- python: 3.5
    #  env: TOXENV=pep8py3

script:
  - echo "Testing"
  - tox
